import crypto from 'crypto'

const ANONYMOUS_ID_LENGTH = 6

export function getAnonymousId(userId: unknown, seed: string = ''): string {
  if (userId == null) return ''
  const str = typeof userId === 'string' ? userId : (userId as { toString(): string }).toString()
  const hash = crypto.createHash('sha256').update(str + seed).digest('hex')
  return hash.slice(0, ANONYMOUS_ID_LENGTH)
}

// source: https://gist.github.com/raineorshine/599777e98e5e968a15c545043973f035
const ANON_ANIMALS = [
  "Aardvark",
  "Aardwolf",
  "African Buffalo",
  "African Elephant",
  "African Leopard",
  "Albatross",
  "Alligator",
  "Alpaca",
  "Amphibian",
  "Anaconda",
  "Angelfish",
  "Anglerfish",
  "Ant",
  "Anteater",
  "Antelope",
  "Antlion",
  "Ape",
  "Aphid",
  "Arabian Leopard",
  "Arctic Fox",
  "Arctic Wolf",
  "Armadillo",
  "Arrow Crab",
  "Asp",
  "Baboon",
  "Bactrian Camel",
  "Badger",
  "Bald Eagle",
  "Bali Cattle",
  "Bandicoot",
  "Barnacle",
  "Barracuda",
  "Basilisk",
  "Bass",
  "Bat",
  "Beaked Whale",
  "Bear",
  "Beaver",
  "Bedbug",
  "Bee",
  "Beetle",
  "Bird",
  "Bison",
  "Black Panther",
  "Black Widow Spider",
  "Blackbird",
  "Blue Bird",
  "Blue Jay",
  "Blue Whale",
  "Boa",
  "Boar",
  "Bobcat",
  "Bobolink",
  "Bonobo",
  "Bovid",
  "Box Jellyfish",
  "Buffalo",
  "Bug",
  "Butterfly",
  "Buzzard",
  "Camel",
  "Canary",
  "Canid",
  "Canidae",
  "Cape Buffalo",
  "Capybara",
  "Cardinal",
  "Caribou",
  "Carp",
  "Cat",
  "Caterpillar",
  "Catfish",
  "Catshark",
  "Cattle",
  "Centipede",
  "Cephalopod",
  "Chameleon",
  "Cheetah",
  "Chickadee",
  "Chicken",
  "Chimpanzee",
  "Chinchilla",
  "Chipmunk",
  "Cicada",
  "Clam",
  "Clownfish",
  "Cobra",
  "Cockroach",
  "Cod",
  "Condor",
  "Constrictor",
  "Coral",
  "Cougar",
  "Cow",
  "Coyote",
  "Crab",
  "Crane Fly",
  "Crane",
  "Crawdad",
  "Crayfish",
  "Cricket",
  "Crocodile",
  "Crow",
  "Cuckoo",
  "Damselfly",
  "Deer",
  "Dingo",
  "Dinosaur",
  "Dog",
  "Dolphin",
  "Donkey",
  "Dormouse",
  "Dove",
  "Dragon",
  "Dragonfly",
  "Dromedary Camel",
  "Duck",
  "Dung Beetle",
  "Eagle",
  "Earthworm",
  "Earwig",
  "Echidna",
  "Eel",
  "Egret",
  "Elephant Seal",
  "Elephant",
  "Elk",
  "Emu",
  "English Pointer",
  "Ermine",
  "Falcon",
  "Fancy Mouse",
  "Fancy Rat Varieties",
  "Fancy Rat",
  "Felidae",
  "Ferret",
  "Finch",
  "Firefly",
  "Fish",
  "Flamingo",
  "Flea",
  "Fly",
  "Flyingfish",
  "Fowl",
  "Fox",
  "Frog",
  "Fruit Bat",
  "Galliform",
  "Gamefowl",
  "Gayal",
  "Gazelle",
  "Gecko",
  "Gerbil",
  "Giant Panda",
  "Giant Squid",
  "Gibbon",
  "Gila Monster",
  "Giraffe",
  "Goat",
  "Goldfish",
  "Goose",
  "Gopher",
  "Gorilla",
  "Grasshopper",
  "Great Blue Heron",
  "Great White Shark",
  "Grizzly Bear",
  "Ground Shark",
  "Ground Sloth",
  "Grouse",
  "Guan",
  "Guanaco",
  "Guinea Pig",
  "Guineafowl",
  "Gull",
  "Guppy",
  "Haddock",
  "Halibut",
  "Hammerhead Shark",
  "Hamster",
  "Hare",
  "Harrier",
  "Hawk",
  "Hedgehog",
  "Hermit Crab",
  "Heron",
  "Herring",
  "Hippopotamus",
  "Hookworm",
  "Hornet",
  "Horse",
  "Hoverfly",
  "Hummingbird",
  "Humpback Whale",
  "Hyena",
  "Iguana",
  "Impala",
  "Irukandji Jellyfish",
  "Jackal",
  "Jaguar",
  "Jay",
  "Jellyfish",
  "Junglefowl",
  "Kangaroo Mouse",
  "Kangaroo Rat",
  "Kangaroo",
  "Kingfisher",
  "Kite",
  "Kiwi",
  "Koala",
  "Koi",
  "Komodo Dragon",
  "Krill",
  "Lab Rat",
  "Ladybug",
  "Lamprey",
  "Land Snail",
  "Landfowl",
  "Lark",
  "Leech",
  "Lemming",
  "Lemur",
  "Leopard",
  "Leopon",
  "Limpet",
  "Lion",
  "Lizard",
  "Llama",
  "Lobster",
  "Locust",
  "Loon",
  "Louse",
  "Lungfish",
  "Lynx",
  "Macaw",
  "Mackerel",
  "Magpie",
  "Mammal",
  "Manatee",
  "Mandrill",
  "Manta Ray",
  "Marlin",
  "Marmoset",
  "Marmot",
  "Marsupial",
  "Marten",
  "Mastodon",
  "Meadowlark",
  "Meerkat",
  "Mink",
  "Minnow",
  "Mite",
  "Mockingbird",
  "Mole",
  "Mollusk",
  "Mongoose",
  "Monitor Lizard",
  "Monkey",
  "Moose",
  "Mosquito",
  "Moth",
  "Mountain Goat",
  "Mouse",
  "Mule",
  "Muskox",
  "Narwhal",
  "New World Quail",
  "Newt",
  "Nightingale",
  "Ocelot",
  "Octopus",
  "Old World Quail",
  "Opossum",
  "Orangutan",
  "Orca",
  "Ostrich",
  "Otter",
  "Owl",
  "Ox",
  "Panda",
  "Panther",
  "Panthera Hybrid",
  "Parakeet",
  "Parrot",
  "Parrotfish",
  "Partridge",
  "Peacock",
  "Peafowl",
  "Pelican",
  "Penguin",
  "Perch",
  "Peregrine Falcon",
  "Pheasant",
  "Pig",
  "Pigeon",
  "Pike",
  "Pilot Whale",
  "Pinniped",
  "Piranha",
  "Planarian",
  "Platypus",
  "Polar Bear",
  "Pony",
  "Porcupine",
  "Porpoise",
  "Portuguese Man O' War",
  "Possum",
  "Prairie Dog",
  "Prawn",
  "Praying Mantis",
  "Primate",
  "Ptarmigan",
  "Puffin",
  "Puma",
  "Python",
  "Quail",
  "Quelea",
  "Quokka",
  "Rabbit",
  "Raccoon",
  "Rainbow Trout",
  "Rat",
  "Rattlesnake",
  "Raven",
  "Ray",
  "Red Panda",
  "Reindeer",
  "Reptile",
  "Rhinoceros",
  "Right Whale",
  "Ringneck Dove",
  "Roadrunner",
  "Robin",
  "Rodent",
  "Rook",
  "Rooster",
  "Roundworm",
  "Saber-toothed Cat",
  "Sailfish",
  "Salamander",
  "Salmon",
  "Sawfish",
  "Scale Insect",
  "Scallop",
  "Scorpion",
  "Sea Lion",
  "Sea Slug",
  "Sea Snail",
  "Seahorse",
  "Shark",
  "Sheep",
  "Shrew",
  "Shrimp",
  "Siamese Fighting Fish",
  "Silkmoth",
  "Silkworm",
  "Silver Fox",
  "Silverfish",
  "Skink",
  "Skunk",
  "Sloth",
  "Slug",
  "Smelt",
  "Snail",
  "Snake",
  "Snipe",
  "Snow Leopard",
  "Society Finch",
  "Sockeye Salmon",
  "Sole",
  "Sparrow",
  "Sperm Whale",
  "Spider Monkey",
  "Spider",
  "Spoonbill",
  "Squid",
  "Squirrel",
  "Star-nosed Mole",
  "Starfish",
  "Steelhead Trout",
  "Stingray",
  "Stoat",
  "Stork",
  "Sturgeon",
  "Sugar Glider",
  "Swallow",
  "Swan",
  "Swift",
  "Swordfish",
  "Swordtail",
  "Tahr",
  "Takin",
  "Tapir",
  "Tarantula",
  "Tarsier",
  "Tasmanian Devil",
  "Termite",
  "Tern",
  "Thrush",
  "Tick",
  "Tiger Shark",
  "Tiger",
  "Tiglon",
  "Toad",
  "Tortoise",
  "Toucan",
  "Trapdoor Spider",
  "Tree Frog",
  "Trout",
  "Tuna",
  "Turkey",
  "Turtle",
  "Tyrannosaurus",
  "Urial",
  "Vampire Bat",
  "Vampire Squid",
  "Vicuna",
  "Viper",
  "Vole",
  "Vulture",
  "Wallaby",
  "Walrus",
  "Warbler",
  "Wasp",
  "Water Boa",
  "Water Buffalo",
  "Weasel",
  "Whale",
  "Whippet",
  "Whitefish",
  "Whooping Crane",
  "Wildcat",
  "Wildebeest",
  "Wildfowl",
  "Wolf",
  "Wolverine",
  "Wombat",
  "Woodpecker",
  "Worm",
  "Wren",
  "X-ray Fish",
  "Xerinae",
  "Yak",
  "Yellow Perch",
  "Zebra Finch",
  "Zebra"
]

function hashCode(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash + str.charCodeAt(i)) | 0
  }
  return Math.abs(hash)
}

export function hashToColor(id?: string): string {
  if (!id) return 'var(--mantine-color-gray-4)'
  const h = hashCode(id) % 360
  return `hsl(${h}, 90%, 80%)`
}

export function getAnonLabel(id?: string): { name: string; initial: string } {
  if (!id) return { name: 'Anonymous', initial: '?' }
  const animal = ANON_ANIMALS[hashCode(id) % ANON_ANIMALS.length]
  return { name: `Anonymous ${animal}`, initial: animal[0] }
}
