import type { NextPage } from 'next'
import Head from 'next/head'

import { Button, Center, Container, Group, Stack, Text, Title } from '@mantine/core'

import classes from '../styles/NotFoundPage.module.css'

const NotFoundPage: NextPage = () => {

  return (
    <Container style={{ height: '90vh' }}>
      <Head>
        <title>404 | MIT OpenGrades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center style={{ height: '100%' }}>
        <Stack>
          <div className={classes.label}>404</div>
          <Title className={classes.title}>You have found a secret place.</Title>
          <Text c="dimmed" size="lg" ta="center" className={classes.description}>
            Just kidding, this is only a 404 page. You may have mistyped the address, or the page has
            been moved to another URL.
          </Text>
          <Group justify="center">
            <Button variant="subtle" size="md">
              Take me home, country roads!
            </Button>
          </Group>
        </Stack>
      </Center>

    </Container>
  )
}

export default NotFoundPage
