// @ts-nocheck

import type { NextPage } from 'next'
import Head from 'next/head'

import { Center, Container, Title } from '@mantine/core'

const Leaderboard: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>MIT OpenGrades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center>
        <Title>
          Leaderboard
        </Title>
      </Center>

    </Container>
  )
}

export default Leaderboard
